### PR TITLE
Team b4

### PR DESCRIPTION
**Pull request by bex1111**
Summary of changes and the sender team

The irrelevant parts must be removed!

# Fixed bugs (with referenced issue)

 - Egocar now turns left pressing left arrow #ISSUE-ID
 - ...

# Added functionalities (with referenced issue)

 - Flux capacitor has been implemented #ISSUE-ID
 - ...

# (Breaking) changes (with referenced issue)

 - getWorldObjectReferencePoint no longer returns the top-left corner
   but the centroid #ISSUE-ID
 - ...

# Other (test, documentation addition, refactor)

 - e.g. Tests added to powertrain
 - Input handling was refactored
 - ...

### CODE REVIEW

**Comment by pintergreg** [comment]
Nullpointer exception-nel elszáll nálam.

```
Exception in thread "main" java.lang.NullPointerException
	at hu.oe.nik.szfmv.automatedcar.systemcomponents.PowertrainSystem.updateEngine(PowertrainSystem.java:53)
	at hu.oe.nik.szfmv.automatedcar.AutomatedCar.drive(AutomatedCar.java:43)
	at hu.oe.nik.szfmv.Main.main(Main.java:39)
```

**Comment by bex1111** [comment]
Nekünk lefut pontosan hogy indítottad el?

**Comment by pintergreg** [comment]
@bex1111 Run Main.main(). Többféleképpen is lehet indítani?

**Comment by bex1111** [comment]
@pintergreg kilett javítva a hiba!

**Pull request merged**
